In [14]:
import torch

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X, X.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [19]:
X[-1], X[1:3, :]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5., 17.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])