In [1]:
import torch

In [4]:
x = torch.arange(6, dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5.])

In [6]:
x.numel()

6

In [7]:
x.shape

torch.Size([6])

In [8]:
X = x.reshape(3, 2)
X

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3, 4)

tensor([[-0.4984,  0.5105, -0.3067, -0.3015],
        [-1.0372, -0.4752, -0.5876,  0.9034],
        [-2.0100,  1.0443, -0.6748,  0.4653]])